protoc --csharp_out D:\Temp Common.proto
protoc --csharp_out D:\Temp GetGlobalState.proto
protoc --csharp_out D:\Temp GetUserInfo.proto
protoc --csharp_out D:\Temp InitConnect.proto
protoc --csharp_out D:\Temp KeepAlive.proto
protoc --csharp_out D:\Temp Notify.proto
protoc --csharp_out D:\Temp Qot_Common.proto
protoc --csharp_out D:\Temp Qot_GetBasicQot.proto
protoc --csharp_out D:\Temp Qot_GetBroker.proto
protoc --csharp_out D:\Temp Qot_GetHistoryKL.proto
protoc --csharp_out D:\Temp Qot_GetHistoryKLPoints.proto
protoc --csharp_out D:\Temp Qot_GetHoldingChangeList.proto
protoc --csharp_out D:\Temp Qot_GetKL.proto
protoc --csharp_out D:\Temp Qot_GetOptionChain.proto
protoc --csharp_out D:\Temp Qot_GetOrderBook.proto
protoc --csharp_out D:\Temp Qot_GetOrderDetail.proto
protoc --csharp_out D:\Temp Qot_GetOwnerPlate.proto
protoc --csharp_out D:\Temp Qot_GetPlateSecurity.proto
protoc --csharp_out D:\Temp Qot_GetPlateSet.proto
protoc --csharp_out D:\Temp Qot_GetReference.proto
protoc --csharp_out D:\Temp Qot_GetRehab.proto
protoc --csharp_out D:\Temp Qot_GetRT.proto
protoc --csharp_out D:\Temp Qot_GetSecuritySnapshot.proto
protoc --csharp_out D:\Temp Qot_GetStaticInfo.proto
protoc --csharp_out D:\Temp Qot_GetSubInfo.proto
protoc --csharp_out D:\Temp Qot_GetSuspend.proto
protoc --csharp_out D:\Temp Qot_GetTicker.proto
protoc --csharp_out D:\Temp Qot_GetTradeDate.proto
protoc --csharp_out D:\Temp Qot_GetWarrant.proto
protoc --csharp_out D:\Temp Qot_RegQotPush.proto
protoc --csharp_out D:\Temp Qot_RequestHistoryKL.proto
protoc --csharp_out D:\Temp Qot_RequestHistoryKLQuota.proto
protoc --csharp_out D:\Temp Qot_RequestRehab.proto
protoc --csharp_out D:\Temp Qot_Sub.proto
protoc --csharp_out D:\Temp Qot_UpdateBasicQot.proto
protoc --csharp_out D:\Temp Qot_UpdateBroker.proto
protoc --csharp_out D:\Temp Qot_UpdateKL.proto
protoc --csharp_out D:\Temp Qot_UpdateOrderBook.proto
protoc --csharp_out D:\Temp Qot_UpdateOrderDetail.proto
protoc --csharp_out D:\Temp Qot_UpdateRT.proto
protoc --csharp_out D:\Temp Qot_UpdateTicker.proto
protoc --csharp_out D:\Temp Trd_Common.proto
protoc --csharp_out D:\Temp Trd_GetAccList.proto
protoc --csharp_out D:\Temp Trd_GetFunds.proto
protoc --csharp_out D:\Temp Trd_GetHistoryOrderFillList.proto
protoc --csharp_out D:\Temp Trd_GetHistoryOrderList.proto
protoc --csharp_out D:\Temp Trd_GetMaxTrdQtys.proto
protoc --csharp_out D:\Temp Trd_GetOrderFillList.proto
protoc --csharp_out D:\Temp Trd_GetOrderList.proto
protoc --csharp_out D:\Temp Trd_GetPositionList.proto
protoc --csharp_out D:\Temp Trd_ModifyOrder.proto
protoc --csharp_out D:\Temp Trd_Notify.proto
protoc --csharp_out D:\Temp Trd_PlaceOrder.proto
protoc --csharp_out D:\Temp Trd_ReconfirmOrder.proto
protoc --csharp_out D:\Temp Trd_SubAccPush.proto
protoc --csharp_out D:\Temp Trd_UnlockTrade.proto
protoc --csharp_out D:\Temp Trd_UpdateOrder.proto
protoc --csharp_out D:\Temp Trd_UpdateOrderFill.proto
protoc --csharp_out D:\Temp Verification.proto