// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Qot_RequestHistoryKL.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace QotRequestHistoryKL {

  /// <summary>Holder for reflection information generated from Qot_RequestHistoryKL.proto</summary>
  public static partial class QotRequestHistoryKLReflection {

    #region Descriptor
    /// <summary>File descriptor for Qot_RequestHistoryKL.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static QotRequestHistoryKLReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChpRb3RfUmVxdWVzdEhpc3RvcnlLTC5wcm90bxIUUW90X1JlcXVlc3RIaXN0",
            "b3J5S0waDENvbW1vbi5wcm90bxoQUW90X0NvbW1vbi5wcm90byK3AQoDQzJT",
            "EhEKCXJlaGFiVHlwZRgBIAEoBRIOCgZrbFR5cGUYAiABKAUSJgoIc2VjdXJp",
            "dHkYAyABKAsyFC5Rb3RfQ29tbW9uLlNlY3VyaXR5EhEKCWJlZ2luVGltZRgE",
            "IAEoCRIPCgdlbmRUaW1lGAUgASgJEhMKC21heEFja0tMTnVtGAYgASgFEhgK",
            "EG5lZWRLTEZpZWxkc0ZsYWcYByABKAMSEgoKbmV4dFJlcUtleRgIIAEoDCJk",
            "CgNTMkMSJgoIc2VjdXJpdHkYASABKAsyFC5Rb3RfQ29tbW9uLlNlY3VyaXR5",
            "EiEKBmtsTGlzdBgCIAMoCzIRLlFvdF9Db21tb24uS0xpbmUSEgoKbmV4dFJl",
            "cUtleRgDIAEoDCIxCgdSZXF1ZXN0EiYKA2MycxgBIAEoCzIZLlFvdF9SZXF1",
            "ZXN0SGlzdG9yeUtMLkMyUyJkCghSZXNwb25zZRIPCgdyZXRUeXBlGAEgASgF",
            "Eg4KBnJldE1zZxgCIAEoCRIPCgdlcnJDb2RlGAMgASgFEiYKA3MyYxgEIAEo",
            "CzIZLlFvdF9SZXF1ZXN0SGlzdG9yeUtMLlMyQ2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Common.CommonReflection.Descriptor, global::QotCommon.QotCommonReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::QotRequestHistoryKL.C2S), global::QotRequestHistoryKL.C2S.Parser, new[]{ "RehabType", "KlType", "Security", "BeginTime", "EndTime", "MaxAckKLNum", "NeedKLFieldsFlag", "NextReqKey" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::QotRequestHistoryKL.S2C), global::QotRequestHistoryKL.S2C.Parser, new[]{ "Security", "KlList", "NextReqKey" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::QotRequestHistoryKL.Request), global::QotRequestHistoryKL.Request.Parser, new[]{ "C2S" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::QotRequestHistoryKL.Response), global::QotRequestHistoryKL.Response.Parser, new[]{ "RetType", "RetMsg", "ErrCode", "S2C" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class C2S : pb::IMessage<C2S> {
    private static readonly pb::MessageParser<C2S> _parser = new pb::MessageParser<C2S>(() => new C2S());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<C2S> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::QotRequestHistoryKL.QotRequestHistoryKLReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public C2S() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public C2S(C2S other) : this() {
      rehabType_ = other.rehabType_;
      klType_ = other.klType_;
      security_ = other.security_ != null ? other.security_.Clone() : null;
      beginTime_ = other.beginTime_;
      endTime_ = other.endTime_;
      maxAckKLNum_ = other.maxAckKLNum_;
      needKLFieldsFlag_ = other.needKLFieldsFlag_;
      nextReqKey_ = other.nextReqKey_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public C2S Clone() {
      return new C2S(this);
    }

    /// <summary>Field number for the "rehabType" field.</summary>
    public const int RehabTypeFieldNumber = 1;
    private int rehabType_;
    /// <summary>
    ///Qot_Common.RehabType,复权类型
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int RehabType {
      get { return rehabType_; }
      set {
        rehabType_ = value;
      }
    }

    /// <summary>Field number for the "klType" field.</summary>
    public const int KlTypeFieldNumber = 2;
    private int klType_;
    /// <summary>
    ///Qot_Common.KLType,K线类型
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int KlType {
      get { return klType_; }
      set {
        klType_ = value;
      }
    }

    /// <summary>Field number for the "security" field.</summary>
    public const int SecurityFieldNumber = 3;
    private global::QotCommon.Security security_;
    /// <summary>
    ///股票市场以及股票代码
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::QotCommon.Security Security {
      get { return security_; }
      set {
        security_ = value;
      }
    }

    /// <summary>Field number for the "beginTime" field.</summary>
    public const int BeginTimeFieldNumber = 4;
    private string beginTime_ = "";
    /// <summary>
    ///开始时间字符串
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string BeginTime {
      get { return beginTime_; }
      set {
        beginTime_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "endTime" field.</summary>
    public const int EndTimeFieldNumber = 5;
    private string endTime_ = "";
    /// <summary>
    ///结束时间字符串
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string EndTime {
      get { return endTime_; }
      set {
        endTime_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "maxAckKLNum" field.</summary>
    public const int MaxAckKLNumFieldNumber = 6;
    private int maxAckKLNum_;
    /// <summary>
    ///最多返回多少根K线，如果未指定表示不限制
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int MaxAckKLNum {
      get { return maxAckKLNum_; }
      set {
        maxAckKLNum_ = value;
      }
    }

    /// <summary>Field number for the "needKLFieldsFlag" field.</summary>
    public const int NeedKLFieldsFlagFieldNumber = 7;
    private long needKLFieldsFlag_;
    /// <summary>
    ///指定返回K线结构体特定某几项数据，KLFields枚举值或组合，如果未指定返回全部字段
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long NeedKLFieldsFlag {
      get { return needKLFieldsFlag_; }
      set {
        needKLFieldsFlag_ = value;
      }
    }

    /// <summary>Field number for the "nextReqKey" field.</summary>
    public const int NextReqKeyFieldNumber = 8;
    private pb::ByteString nextReqKey_ = pb::ByteString.Empty;
    /// <summary>
    ///分页请求key
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb::ByteString NextReqKey {
      get { return nextReqKey_; }
      set {
        nextReqKey_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as C2S);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(C2S other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (RehabType != other.RehabType) return false;
      if (KlType != other.KlType) return false;
      if (!object.Equals(Security, other.Security)) return false;
      if (BeginTime != other.BeginTime) return false;
      if (EndTime != other.EndTime) return false;
      if (MaxAckKLNum != other.MaxAckKLNum) return false;
      if (NeedKLFieldsFlag != other.NeedKLFieldsFlag) return false;
      if (NextReqKey != other.NextReqKey) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (RehabType != 0) hash ^= RehabType.GetHashCode();
      if (KlType != 0) hash ^= KlType.GetHashCode();
      if (security_ != null) hash ^= Security.GetHashCode();
      if (BeginTime.Length != 0) hash ^= BeginTime.GetHashCode();
      if (EndTime.Length != 0) hash ^= EndTime.GetHashCode();
      if (MaxAckKLNum != 0) hash ^= MaxAckKLNum.GetHashCode();
      if (NeedKLFieldsFlag != 0L) hash ^= NeedKLFieldsFlag.GetHashCode();
      if (NextReqKey.Length != 0) hash ^= NextReqKey.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (RehabType != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(RehabType);
      }
      if (KlType != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(KlType);
      }
      if (security_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Security);
      }
      if (BeginTime.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(BeginTime);
      }
      if (EndTime.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(EndTime);
      }
      if (MaxAckKLNum != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(MaxAckKLNum);
      }
      if (NeedKLFieldsFlag != 0L) {
        output.WriteRawTag(56);
        output.WriteInt64(NeedKLFieldsFlag);
      }
      if (NextReqKey.Length != 0) {
        output.WriteRawTag(66);
        output.WriteBytes(NextReqKey);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (RehabType != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(RehabType);
      }
      if (KlType != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(KlType);
      }
      if (security_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Security);
      }
      if (BeginTime.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(BeginTime);
      }
      if (EndTime.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(EndTime);
      }
      if (MaxAckKLNum != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(MaxAckKLNum);
      }
      if (NeedKLFieldsFlag != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(NeedKLFieldsFlag);
      }
      if (NextReqKey.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(NextReqKey);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(C2S other) {
      if (other == null) {
        return;
      }
      if (other.RehabType != 0) {
        RehabType = other.RehabType;
      }
      if (other.KlType != 0) {
        KlType = other.KlType;
      }
      if (other.security_ != null) {
        if (security_ == null) {
          Security = new global::QotCommon.Security();
        }
        Security.MergeFrom(other.Security);
      }
      if (other.BeginTime.Length != 0) {
        BeginTime = other.BeginTime;
      }
      if (other.EndTime.Length != 0) {
        EndTime = other.EndTime;
      }
      if (other.MaxAckKLNum != 0) {
        MaxAckKLNum = other.MaxAckKLNum;
      }
      if (other.NeedKLFieldsFlag != 0L) {
        NeedKLFieldsFlag = other.NeedKLFieldsFlag;
      }
      if (other.NextReqKey.Length != 0) {
        NextReqKey = other.NextReqKey;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            RehabType = input.ReadInt32();
            break;
          }
          case 16: {
            KlType = input.ReadInt32();
            break;
          }
          case 26: {
            if (security_ == null) {
              Security = new global::QotCommon.Security();
            }
            input.ReadMessage(Security);
            break;
          }
          case 34: {
            BeginTime = input.ReadString();
            break;
          }
          case 42: {
            EndTime = input.ReadString();
            break;
          }
          case 48: {
            MaxAckKLNum = input.ReadInt32();
            break;
          }
          case 56: {
            NeedKLFieldsFlag = input.ReadInt64();
            break;
          }
          case 66: {
            NextReqKey = input.ReadBytes();
            break;
          }
        }
      }
    }

  }

  public sealed partial class S2C : pb::IMessage<S2C> {
    private static readonly pb::MessageParser<S2C> _parser = new pb::MessageParser<S2C>(() => new S2C());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<S2C> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::QotRequestHistoryKL.QotRequestHistoryKLReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public S2C() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public S2C(S2C other) : this() {
      security_ = other.security_ != null ? other.security_.Clone() : null;
      klList_ = other.klList_.Clone();
      nextReqKey_ = other.nextReqKey_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public S2C Clone() {
      return new S2C(this);
    }

    /// <summary>Field number for the "security" field.</summary>
    public const int SecurityFieldNumber = 1;
    private global::QotCommon.Security security_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::QotCommon.Security Security {
      get { return security_; }
      set {
        security_ = value;
      }
    }

    /// <summary>Field number for the "klList" field.</summary>
    public const int KlListFieldNumber = 2;
    private static readonly pb::FieldCodec<global::QotCommon.KLine> _repeated_klList_codec
        = pb::FieldCodec.ForMessage(18, global::QotCommon.KLine.Parser);
    private readonly pbc::RepeatedField<global::QotCommon.KLine> klList_ = new pbc::RepeatedField<global::QotCommon.KLine>();
    /// <summary>
    ///K线数据
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::QotCommon.KLine> KlList {
      get { return klList_; }
    }

    /// <summary>Field number for the "nextReqKey" field.</summary>
    public const int NextReqKeyFieldNumber = 3;
    private pb::ByteString nextReqKey_ = pb::ByteString.Empty;
    /// <summary>
    ///分页请求key。一次请求没有返回所有数据时，下次请求带上这个key，会接着请求
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb::ByteString NextReqKey {
      get { return nextReqKey_; }
      set {
        nextReqKey_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as S2C);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(S2C other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Security, other.Security)) return false;
      if(!klList_.Equals(other.klList_)) return false;
      if (NextReqKey != other.NextReqKey) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (security_ != null) hash ^= Security.GetHashCode();
      hash ^= klList_.GetHashCode();
      if (NextReqKey.Length != 0) hash ^= NextReqKey.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (security_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Security);
      }
      klList_.WriteTo(output, _repeated_klList_codec);
      if (NextReqKey.Length != 0) {
        output.WriteRawTag(26);
        output.WriteBytes(NextReqKey);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (security_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Security);
      }
      size += klList_.CalculateSize(_repeated_klList_codec);
      if (NextReqKey.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(NextReqKey);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(S2C other) {
      if (other == null) {
        return;
      }
      if (other.security_ != null) {
        if (security_ == null) {
          Security = new global::QotCommon.Security();
        }
        Security.MergeFrom(other.Security);
      }
      klList_.Add(other.klList_);
      if (other.NextReqKey.Length != 0) {
        NextReqKey = other.NextReqKey;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (security_ == null) {
              Security = new global::QotCommon.Security();
            }
            input.ReadMessage(Security);
            break;
          }
          case 18: {
            klList_.AddEntriesFrom(input, _repeated_klList_codec);
            break;
          }
          case 26: {
            NextReqKey = input.ReadBytes();
            break;
          }
        }
      }
    }

  }

  public sealed partial class Request : pb::IMessage<Request> {
    private static readonly pb::MessageParser<Request> _parser = new pb::MessageParser<Request>(() => new Request());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Request> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::QotRequestHistoryKL.QotRequestHistoryKLReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Request() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Request(Request other) : this() {
      c2S_ = other.c2S_ != null ? other.c2S_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Request Clone() {
      return new Request(this);
    }

    /// <summary>Field number for the "c2s" field.</summary>
    public const int C2SFieldNumber = 1;
    private global::QotRequestHistoryKL.C2S c2S_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::QotRequestHistoryKL.C2S C2S {
      get { return c2S_; }
      set {
        c2S_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Request);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Request other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(C2S, other.C2S)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (c2S_ != null) hash ^= C2S.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (c2S_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(C2S);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (c2S_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(C2S);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Request other) {
      if (other == null) {
        return;
      }
      if (other.c2S_ != null) {
        if (c2S_ == null) {
          C2S = new global::QotRequestHistoryKL.C2S();
        }
        C2S.MergeFrom(other.C2S);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (c2S_ == null) {
              C2S = new global::QotRequestHistoryKL.C2S();
            }
            input.ReadMessage(C2S);
            break;
          }
        }
      }
    }

  }

  public sealed partial class Response : pb::IMessage<Response> {
    private static readonly pb::MessageParser<Response> _parser = new pb::MessageParser<Response>(() => new Response());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Response> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::QotRequestHistoryKL.QotRequestHistoryKLReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Response() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Response(Response other) : this() {
      retType_ = other.retType_;
      retMsg_ = other.retMsg_;
      errCode_ = other.errCode_;
      s2C_ = other.s2C_ != null ? other.s2C_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Response Clone() {
      return new Response(this);
    }

    /// <summary>Field number for the "retType" field.</summary>
    public const int RetTypeFieldNumber = 1;
    private int retType_;
    /// <summary>
    ///RetType,返回结果
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int RetType {
      get { return retType_; }
      set {
        retType_ = value;
      }
    }

    /// <summary>Field number for the "retMsg" field.</summary>
    public const int RetMsgFieldNumber = 2;
    private string retMsg_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string RetMsg {
      get { return retMsg_; }
      set {
        retMsg_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "errCode" field.</summary>
    public const int ErrCodeFieldNumber = 3;
    private int errCode_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int ErrCode {
      get { return errCode_; }
      set {
        errCode_ = value;
      }
    }

    /// <summary>Field number for the "s2c" field.</summary>
    public const int S2CFieldNumber = 4;
    private global::QotRequestHistoryKL.S2C s2C_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::QotRequestHistoryKL.S2C S2C {
      get { return s2C_; }
      set {
        s2C_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Response);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Response other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (RetType != other.RetType) return false;
      if (RetMsg != other.RetMsg) return false;
      if (ErrCode != other.ErrCode) return false;
      if (!object.Equals(S2C, other.S2C)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (RetType != 0) hash ^= RetType.GetHashCode();
      if (RetMsg.Length != 0) hash ^= RetMsg.GetHashCode();
      if (ErrCode != 0) hash ^= ErrCode.GetHashCode();
      if (s2C_ != null) hash ^= S2C.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (RetType != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(RetType);
      }
      if (RetMsg.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(RetMsg);
      }
      if (ErrCode != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(ErrCode);
      }
      if (s2C_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(S2C);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (RetType != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(RetType);
      }
      if (RetMsg.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(RetMsg);
      }
      if (ErrCode != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ErrCode);
      }
      if (s2C_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(S2C);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Response other) {
      if (other == null) {
        return;
      }
      if (other.RetType != 0) {
        RetType = other.RetType;
      }
      if (other.RetMsg.Length != 0) {
        RetMsg = other.RetMsg;
      }
      if (other.ErrCode != 0) {
        ErrCode = other.ErrCode;
      }
      if (other.s2C_ != null) {
        if (s2C_ == null) {
          S2C = new global::QotRequestHistoryKL.S2C();
        }
        S2C.MergeFrom(other.S2C);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            RetType = input.ReadInt32();
            break;
          }
          case 18: {
            RetMsg = input.ReadString();
            break;
          }
          case 24: {
            ErrCode = input.ReadInt32();
            break;
          }
          case 34: {
            if (s2C_ == null) {
              S2C = new global::QotRequestHistoryKL.S2C();
            }
            input.ReadMessage(S2C);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
